[versions]
library = "0.0.1"
kotlin = "2.2.20"
ktor_version="3.3.2"
maven-publish = "0.35.0"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor_version" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor_version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }